name: foodtruck
description: A quick and easy FoodTruck location application.  Locate your favorite Food Trucks fast!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.1+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.3
  google_maps_flutter:
  geolocator: ^7.5.0
  font_awesome_flutter: ^9.1.0
  get_storage: ^2.0.3
  location: ^4.3.0
  url_launcher: ^6.0.9
  smooth_star_rating: ^1.1.1
  carousel_pro: ^1.0.0
  shared_preferences: ^2.0.7
  image_picker: ^0.8.3+3
  video_player: ^2.1.14
  statusbar: ^1.1.0
  permission_handler: ^8.1.4+2
  admob_flutter: ^2.0.0
  fluttertoast: ^8.0.8
  provider: ^6.0.0
  flare_flutter: ^3.0.2
  http: ^0.13.3
#  google_sign_in: ^5.0.1 TODO:  configure google sign in 
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  upgrader: ^3.11.0
  rive: ^0.8.1
  introduction_screen: ^2.1.0
#  rive: ^0.7.33 todo  new intro animtion

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon-bg.png"
  adaptive_icon_foreground: "assets/icon/icon-front.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/truckIcon.png
    - assets/anim/ntro.riv
    - assets/mapstyle.txt

  fonts:
    - family: Arial
    - fonts:
        - asset: assets/fonts/Arial.ttf
    - family: Futura
    - fonts:
        - asset: assets/fonts/futur.ttf
        - asset: assets/fonts/Futura-Bold-font.ttf
        - asset: assets/fonts/Futura-Book-Italic-font.ttf
        - asset: assets/fonts/Futura-Bold-Italic-font.ttf
